### ISSUE TITLE
서버 이슈

### ISSUE THREAD

**Issue by dhalsdyd** [doch2/SouP#13]
![image](https://user-images.githubusercontent.com/60055699/164382246-d2e62250-3f09-49de-b404-e1f52d08aec4.png)
처음에는 괜찮았는데
요청 시간이 너무 길어졌습니다!

**Comment by doch2** [comment]
지금 다시 한번 해보시겠어요? 서버 수정했습니다

**Comment by dhalsdyd** [comment]
잘 작동합니다!
