### ISSUE TITLE
예수금 정보를 어디서 가져오나요오?

### ISSUE THREAD

**Issue by dhalsdyd** [doch2/SouP#2]

**Comment by doch2** [comment]
예수금은 지금 개발하고 있는 xingapi_flutter_plugin에서 함수로 불러올 예정이에요!
함수 관련 예시는 추후에 플러그인 Repository에 추가할 예정이라, 일단은 더미데이터로 개발 진행하면 될 것 같습니다.
플러그인 개발 끝나면 따로 알림 드릴게요!
